### ISSUE TITLE
addAVUMetadata returning an error with irods 4.3.0

### ISSUE THREAD

**Issue by flelayo** [DICE-UNC/jargon#415] opened 2022-08-03 09:51 UTC
### iRODS Version, OS and Version
irods 4.3.0, centos 7
Jargon 4.3.2.5-RELEASE

### What did you try to do?
Adding a metadata to an existing file using API with Jargon function addAVUMetadata.

### Expected behavior
Metadata added

### Observed behavior (including steps to reproduce, if applicable)
We updated a 4.2.7 irods server on centos7 using yum update. We have done some test with an application that worked fine before update but get us this error now :

```
{"log_category":"legacy","log_facility":"local0","log_level":"info",
"log_message":"rsApiHandler: unpackStruct error for apiNumber 706, status = -15000",
"request_api_name":"MOD_AVU_METADATA_AN","request_api_number":706,"request_api_version":"d",...
```

The XML message send by Jargon seems fine, so I don't understand why there is an error at unpack :

```
<ModAVUMetadataInp_PI><arg0>add</arg0>
<arg1>-d</arg1>
<arg2>/odin/kdi-valid/dataset/100005/archive/file.test</arg2>
<arg3>projectName</arg3>
<arg4>TestProject2</arg4>
<arg5></arg5>
<arg6></arg6>
<arg7></arg7>
<arg8></arg8>
<arg9></arg9>
</ModAVUMetadataInp_PI>
```

We used the API to create the file and do some right management before. Those calls worked.

I thought this was an Irods error but the imeta command add metadata without errors.

**Comment by JustinKyleJames** [comment] 2023-01-10 21:22
This seems to be the cause of irods-contrib/metalnx-web#337

**Comment by JustinKyleJames** [comment] 2023-01-10 22:01
Jargon needs to be updated to add the condInput which was added in 4.3.   Here is an example:

```<ModAVUMetadataInp_PI>
<arg0>add</arg0>
<arg1>-d</arg1>
<arg2>/tempZone/home/rods/2901778.jpg</arg2>
<arg3>a</arg3>
<arg4>b</arg4>
<arg5></arg5>
<arg6></arg6>
<arg7></arg7>
<arg8></arg8>
<arg9></arg9>
<KeyValPair_PI>
<ssLen>0</ssLen>
</KeyValPair_PI>
</ModAVUMetadataInp_PI>```

**Comment by JustinKyleJames** [comment] 2023-01-11 15:27
I added a pull request #417 to fix this.

**Comment by trel** [comment] 2023-03-27 01:18
closing as fixed.

**Closed by trel** 2023-03-27 01:18 UTC
Labels: bug
