### ISSUE TITLE
Slow Jargon API response times with iDROP over SSL

### ISSUE THREAD

**Issue by marc-flesch** [DICE-UNC/jargon#134] opened 2015-07-07 12:16 UTC
Hi All,

I'm using iDROP with PAM (SSL) authentication on our iRODS installation. iCAT and Resource server on the same machine (Version 4.1.3). The iDROP version is (2.0.1-RC1 on Jargon 4.0.2.1-SNAPSHOT).

We observe random hangings (up to a minute) during folder listings from iDROP. The blocking time seems to be independent of the collection size we try to list.
We observe the same issue, in case of using the Jargon API directly. See the following log that was obtained during the hanging call:

```
Jul  7 14:06:08 pid:9491 NOTICE: Agent process 35573 started for puser=marc and cuser=marc from 172.20.144.64
Authenticated
Jul  7 14:06:08 pid:35573 ERROR: [-]    iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Jul  7 14:06:08 pid:35573 NOTICE: Agent exiting with status = -4000
Jul  7 14:06:08 pid:9491 NOTICE: Agent process 35577 started for puser=marc and cuser=marc from 172.20.144.64
Jul  7 14:06:08 pid:35577 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jul  7 14:06:08 pid:35577 NOTICE: Agent exiting with status = 0
Jul  7 14:06:09 pid:9491 NOTICE: Agent process 35573 exited with status 24576
Jul  7 14:06:09 pid:9491 NOTICE: Agent process 35577 exited with status 0
Jul  7 14:06:09 pid:9491 NOTICE: Agent process 35580 started for puser=marc and cuser=marc from 172.20.144.64
Authenticated
Jul  7 14:06:10 pid:35580 ERROR: [-]    iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Jul  7 14:06:10 pid:35580 NOTICE: Agent exiting with status = -4000
Jul  7 14:06:10 pid:9491 NOTICE: Agent process 35580 exited with status 24576
Jul  7 14:07:40 pid:9491 ERROR: readWorkerTask - readStartupPack failed. -4107
Jul  7 14:07:40 pid:9491 NOTICE: Agent process 36968 started for puser=marc and cuser=marc from 172.20.144.64
Jul  7 14:07:40 pid:36968 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jul  7 14:07:40 pid:36968 NOTICE: Agent exiting with status = 0
Jul  7 14:07:40 pid:9491 NOTICE: Agent process 36968 exited with status 0
Jul  7 14:07:43 pid:9491 ERROR: readWorkerTask - readStartupPack failed. -4107
Jul  7 14:07:43 pid:9491 ERROR: readWorkerTask - readStartupPack failed. -4107
Jul  7 14:07:48 pid:9491 ERROR: readWorkerTask - readStartupPack failed. -4107
Jul  7 14:07:50 pid:9491 ERROR: readWorkerTask - readStartupPack failed. -4107
```

The timeout can be observed in the log at: `14:06:10` to `14:07:40`.

In particular the error:

```
readWorkerTask - readStartupPack failed. -4107
```

only occurs  in case of the hanging listing.

Using the regular authentication mechanism (Standard) there is no delay or hanging observed. The issue seems to be related to either SSL or PAM itself.

Any suggestion what to try next?

Best Regards,

Marc Flesch

**Comment by marc-flesch** [comment] 2015-07-21 06:38
Dear Support team,

did anyone already look into this? Could this problem reproduced at your end, or did anyone else report a similar problem before?

Thanks for your advice in advance,

Marc.

**Comment by michael-conway** [comment] 2015-07-21 11:26
Hi Marc

In the Issue4 branch of Jargon I'm working on adding client/server
negotiation and TLS support, as I develop the functional testing for this
enhancement, I will be looking at this issue as well.

I had not seen it before, but I suspect it may be in that processing.  I
have not, to date, had an infrastructure to try various ssl transport
configurations and I'm having to stand one up to do this TLS support.

MC

**Comment by michael-conway** [comment] 2016-11-29 16:37
This is a duplicate of issue #4 which is being merged today

**Closed by michael-conway** 2016-11-29 16:37 UTC
Labels: A
